export interface ActualBuyersType {
    actualbuyerId : number,
    clientactualbuyer : string,
    nameactualbuyer : string,
    addressactualbuyer : string,
    telnoactualbuyer : string,
    emailactualbuyer : string,
    contactactualbuyer : string,
    designationactualbuyer : string,
    cityactualbuyer : string,
    stateactualbuyer : string,
    PIN : string,
    countryactualbuyer : string,
    faxnoactualbuyer : string,
    websiteactualbuyer : string,
    cstactualbuyer : string,
    gstnactualbuyer : string,
    actualbuyergstnote : string,
  };