import { Options } from "@shared/index";

export interface CompanyFormType {
  id?: string;
  address: string;
  bankers: string;
  bulkEnquiryId: number;
  cityId: Options;
  cityName: string;
  cmie: string;
  companyName: string;
  companyRegNo: string;
  companyType: number;
  contactPerson: string;
  countryId: Options;
  countryName: string;
  designation: string;
  email: string;
  enteredBy: number;
  fax: string;
  financialYear: string;
  givenName: string;
  hsCode: string;
  incorporationDate: string;
  modifiedBy: number;
  notes: string;
  ourRefNo: string;
  phone: string;
  recFin: string;
  records: string;
  regdOffice: string;
  reportFileName: string;
  reportFilePath: string;
  rocStatus: string;
  state: string;
  stateId: Options;
  status: number;
  website: string;
  zip: string;
}
