import { Options } from "@shared/index";

export interface ClientFormType {
  id?: number;
  clientId: number;
  ourRefNo: string;
  clientName: string;
  address: string;
  cityId: Options;
  zip: string;
  stateId: Options;
  countryId: Options;
  phone: string;
  fax: string;
  website: string;
  contactPerson: string;
  designation: string;
  currencyId: Options;
  nickName: string;
  executiveId: Options;
  osListPrInteger: string;
  monthlyInvoice: string;
  enteredBy: number;
  enteredDate: string;
  modifiedBy: number;
  modifiedDate: string;
  priorityId: number;
  instruction: string;
  groupId: Options;
  disType: string;
  discount: number;
  toAdjust: number;
  balToAdjust: number;
  adjustPerEnq: number;
  individualReport: string;
  staxApplicable: string;
  remarks: string;
  adjustFromDate: string;
  segmentId: Options;
  toAdjustPI: number;
  balToAdjustPI: number;
  adjustPerEnqPI: number;
  crDays: Options;
  gstn: string;
  gstyn: string;
  billOnActualBuyer: string | boolean;
  autoSendOutstanding: string;
  locked: string;
  email: string;
  stateCode: number;
}
