// import { Options } from "@shared/index";

export interface InvoiceGenGstTableType {
  // clientField: Options;
  // currencyField: string;
  // gstnField: string;
  // actualBuyerField: string;
  // gstnActualBuyreField: string;
  // gstActualBuyreField: string;
  // stateActualBuyreField: Options;
  // fromdateField: string;
  // countryField: string;
  // stateField: Options;
  // codeField: string;
  // gstField: string;
  // todateeField: string;
  // symbolField: string;
  // currencyInwardField: string;
  currencyName: null;
  discountAmount: number;
  stPer: number;
  stAmount: number;
  currencyId: number;
  edCessAmount: null;
  cgstPer: null;
  sgstPer: null;
  igstPer: null;
  cgstAmount: null;
  sgstAmount: null;
  igstAmount: null;
  partyName: null;
  creditPeriod: null;
  outsatndingAmount: null;
  receivedAmount: null;
  expneses: null;
  tds: null;
  clientName: string;
  clientAddress: null;
  clientRefNo: string;
  finYear: string;
  chaqueAmount: null;
  clientId: number;
  invoiceDate: string;
  total: number;
  actualBuyerId: null;
  locked: null;
  invoiceNo: string;
  oldFormat: null;
  staxAmount: null;
  subTotal: number;
  serviceTax: number;
  eduCess: number;
  serviceTaxPer: null;
  edCessPer: null;
  locked_STaxSubmitted: null;
  krishiCessPer: null;
  krishiCessAmt: null;
  crDays: null;
  bankName: null;
  billAmount: number;
  enteredBy: null;
  enteredDate: null;
  modifiedBy: null;
}
