export interface SaveInvoiceFormRequestType {
  invoiceMasterDto: {
    invoiceNo: string;
    invoiceDate: string;
    clientId: string;
    billAmt: number;
    subTotal: number;
    total: number;
    currencyId: number;
    serviceTax: number;
    eduCess: number;
    edCessAmt: number;
    serviceTaxPer: number;
    edCessPer: number;
    lockedSTaxSubmitted: string;
    oldFormat: string;
    krishiCessPer: number;
    krishiCessAmt: number;
    actualBuyerId?: number;
    crDays: number;
    locked: string;
    disAmt: number;
    stper: number;
    stamt: number;
    staxAmt: number;
    cgstper: number;
    sgstper: number;
    igstper: number;
    cgstamt: number;
    sgstamt: number;
    igstamt: number;
    fyear: string;
  };
  enquiryId: Array<number>;
}

// [
//     {
//       refNo: string;
//       partyName: string;
//       clientName: string;
//       clientAddress: string;
//       enqId: number;
//       fyear: number;
//       bookNo: string;
//       dueDate: string;
//       serviceTypeId: number;
//       clientRefNo: string;
//       sourceId: number;
//       enqStatusId: number;
//       notes: string;
//       pmtStatus: string;
//       creditAmount: string;
//       reportDate: string;
//       givenAddress: string;
//       cityId: number;
//       zip: string;
//       stateId: number;
//       countryId: number;
//       cmie: string;
//       rockStatus: string;
//       records: string;
//       recFin: string;
//       phone: string;
//       fax: string;
//       email: string;
//       website: string;
//       contactPerson: string;
//       designation: string;
//       financialYear: string;
//       bankers: string;
//       requestNo: string;
//       instruction: string;
//       reportFilename: string;
//       reportPrice: number;
//       recdDate: string;
//       remarks: string;
//       clientId: number;
//       reportComission: number;
//       typeofEnquiry: string;
//       lineOfBusiness: string;
//       noteForComission: string;
//       industryId: number;
//       disPer: number;
//       discount: number;
//       adjustment: number;
//       disType: string;
//       actualBuyerId: number;
//       siteStatusId: number;
//       bulkEnquiryId: number;
//       locked: string;
//       companyId: number;
//       clientRef: string;
//       enteredBy: number;
//       enteredDate: string;
//       modifiedBy: number;
//       modifiedDate: string;
//       enquiryStatus: string;
//       stateName: string;
//       executiveId: string;
//       cityName: string;
//       countryName: string;
//       groupName: string;
//       sourceName: string;
//       industryName: string;
//       siteStatus: string;
//       serviceTypeName: string;
//       executiveName: string;
//       clientEmail: string;
//       printStatus: string;
//       clientPrice: string;
//       localSource: string;
//       clientCityName: string;
//       clientCountryName: string;
//       clientState: string;
//       companyName: string;
//       clientContactPerson: string;
//       clientFax: string;
//       clientDesignation: string;
//       clientZip: string;
//       clientPhone: string;
//     }
//   ];
